name: don-env-local
services:
  app:
    build:
      dockerfile: build/Dockerfile
    stdin_open: true
    tty: true
  db:
    image: postgres:15
    container_name: don-postgres-local
    ports:
      - "5432:5432"
