// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (id, name, kind, metadata)
VALUES ($1, $2, $3, $4) RETURNING id, name, kind, created_at, updated_at, metadata
`

type CreateBucketParams struct {
	ID       uuid.UUID
	Name     string
	Kind     string
	Metadata json.RawMessage
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, createBucket,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Metadata,
	)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getBuckets = `-- name: GetBuckets :many
SELECT id, name, kind, created_at, updated_at, metadata FROM buckets
`

func (q *Queries) GetBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, getBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bucket
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentBucketBalance = `-- name: GetCurrentBucketBalance :one
SELECT
    COALESCE(SUM(d.initial_balance_cents), 0) +
    COALESCE((
        SELECT SUM(
            CASE
                WHEN dr.increases = true THEN dr.amount_cents
                ELSE -dr.amount_cents
            END
        )
        FROM drips dr
        JOIN droplets inner_d ON dr.droplet_id = inner_d.id
        WHERE inner_d.bucket_id = $1
    ), 0) AS total_bucket_balance
FROM droplets d
WHERE d.bucket_id = $1
`

func (q *Queries) GetCurrentBucketBalance(ctx context.Context, bucketID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentBucketBalance, bucketID)
	var total_bucket_balance int32
	err := row.Scan(&total_bucket_balance)
	return total_bucket_balance, err
}
