// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (id, name, kind, metadata)
VALUES ($1, $2, $3, $4) RETURNING id, name, kind, created_at, updated_at, metadata
`

type CreateBucketParams struct {
	ID       uuid.UUID
	Name     string
	Kind     string
	Metadata json.RawMessage
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, createBucket,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Metadata,
	)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getBuckets = `-- name: GetBuckets :many
SELECT id, name, kind, created_at, updated_at, metadata FROM buckets
`

func (q *Queries) GetBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, getBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bucket
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
