// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (id, name, metadata)
VALUES ($1, $2, $3) RETURNING id, name, slug, created_at, updated_at, metadata
`

type CreateBucketParams struct {
	ID       uuid.UUID
	Name     string
	Metadata json.RawMessage
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, createBucket, arg.ID, arg.Name, arg.Metadata)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getBuckets = `-- name: GetBuckets :many
SELECT id, name, slug, created_at, updated_at, metadata FROM buckets
`

func (q *Queries) GetBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, getBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bucket
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentBucketBalance = `-- name: GetCurrentBucketBalance :one
SELECT
    COALESCE((
        SELECT SUM(
            CASE
                WHEN d.increases = true THEN d.amount_cents
                ELSE -d.amount_cents
            END
        )
        FROM droplets d
        WHERE d.bucket_id = $1
    ), 0) AS total_bucket_balance
WHERE d.bucket_id = $1
`

func (q *Queries) GetCurrentBucketBalance(ctx context.Context, bucketID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getCurrentBucketBalance, bucketID)
	var total_bucket_balance interface{}
	err := row.Scan(&total_bucket_balance)
	return total_bucket_balance, err
}
