// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drips.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createDrip = `-- name: CreateDrip :one
INSERT INTO drips (droplet_id, increases, amount_cents, metadata) VALUES ($1, $2, $3, $4) RETURNING id, droplet_id, increases, amount_cents, created_at, updated_at, metadata
`

type CreateDripParams struct {
	DropletID   uuid.UUID
	Increases   bool
	AmountCents int32
	Metadata    json.RawMessage
}

func (q *Queries) CreateDrip(ctx context.Context, arg CreateDripParams) (Drip, error) {
	row := q.db.QueryRow(ctx, createDrip,
		arg.DropletID,
		arg.Increases,
		arg.AmountCents,
		arg.Metadata,
	)
	var i Drip
	err := row.Scan(
		&i.ID,
		&i.DropletID,
		&i.Increases,
		&i.AmountCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getDrips = `-- name: GetDrips :many
SELECT id, droplet_id, increases, amount_cents, created_at, updated_at, metadata FROM drips
`

func (q *Queries) GetDrips(ctx context.Context) ([]Drip, error) {
	rows, err := q.db.Query(ctx, getDrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drip
	for rows.Next() {
		var i Drip
		if err := rows.Scan(
			&i.ID,
			&i.DropletID,
			&i.Increases,
			&i.AmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
