// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: droplets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createDroplet = `-- name: CreateDroplet :one
INSERT INTO droplets (bucket_id, name, initial_balance_cents) VALUES ($1, $2, $3) RETURNING id, bucket_id, name, initial_balance_cents, created_at, updated_at, metadata
`

type CreateDropletParams struct {
	BucketID            uuid.UUID
	Name                string
	InitialBalanceCents int32
}

func (q *Queries) CreateDroplet(ctx context.Context, arg CreateDropletParams) (Droplet, error) {
	row := q.db.QueryRow(ctx, createDroplet, arg.BucketID, arg.Name, arg.InitialBalanceCents)
	var i Droplet
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Name,
		&i.InitialBalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getCurrentDropletBalance = `-- name: GetCurrentDropletBalance :one
WITH drip_totals AS (
    SELECT
        COALESCE(SUM(amount_cents) FILTER (WHERE increases = true), 0) AS pos_var,
        COALESCE(SUM(amount_cents) FILTER (WHERE increases = false), 0) AS neg_var
    FROM drips
    WHERE droplet_id = $1
)
SELECT d.initial_balance_cents + t.pos_var - t.neg_var AS current_balance
FROM droplets d
CROSS JOIN drip_totals t
WHERE d.id = $1
`

func (q *Queries) GetCurrentDropletBalance(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentDropletBalance, id)
	var current_balance int32
	err := row.Scan(&current_balance)
	return current_balance, err
}

const getDropletById = `-- name: GetDropletById :one
SELECT id, bucket_id, name, initial_balance_cents, created_at, updated_at, metadata FROM droplets WHERE id = $1
`

func (q *Queries) GetDropletById(ctx context.Context, id uuid.UUID) (Droplet, error) {
	row := q.db.QueryRow(ctx, getDropletById, id)
	var i Droplet
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Name,
		&i.InitialBalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getDroplets = `-- name: GetDroplets :many
SELECT id, bucket_id, name, initial_balance_cents, created_at, updated_at, metadata FROM droplets
`

func (q *Queries) GetDroplets(ctx context.Context) ([]Droplet, error) {
	rows, err := q.db.Query(ctx, getDroplets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Droplet
	for rows.Next() {
		var i Droplet
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Name,
			&i.InitialBalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDropletsByBucket = `-- name: GetDropletsByBucket :many
SELECT id, bucket_id, name, initial_balance_cents, created_at, updated_at, metadata FROM droplets WHERE bucket_id = $1
`

func (q *Queries) GetDropletsByBucket(ctx context.Context, bucketID uuid.UUID) ([]Droplet, error) {
	rows, err := q.db.Query(ctx, getDropletsByBucket, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Droplet
	for rows.Next() {
		var i Droplet
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Name,
			&i.InitialBalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
