// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: droplets.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createDroplet = `-- name: CreateDroplet :one
INSERT INTO droplets (bucket_id, increases, amount_cents, metadata) VALUES ($1, $2, $3, $4) RETURNING id, bucket_id, increases, amount_cents, created_at, metadata
`

type CreateDropletParams struct {
	BucketID    uuid.UUID
	Increases   bool
	AmountCents int32
	Metadata    json.RawMessage
}

func (q *Queries) CreateDroplet(ctx context.Context, arg CreateDropletParams) (Droplet, error) {
	row := q.db.QueryRow(ctx, createDroplet,
		arg.BucketID,
		arg.Increases,
		arg.AmountCents,
		arg.Metadata,
	)
	var i Droplet
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Increases,
		&i.AmountCents,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getDropletById = `-- name: GetDropletById :one
SELECT id, bucket_id, increases, amount_cents, created_at, metadata FROM droplets WHERE id = $1
`

func (q *Queries) GetDropletById(ctx context.Context, id uuid.UUID) (Droplet, error) {
	row := q.db.QueryRow(ctx, getDropletById, id)
	var i Droplet
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Increases,
		&i.AmountCents,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getDroplets = `-- name: GetDroplets :many
SELECT id, bucket_id, increases, amount_cents, created_at, metadata FROM droplets
`

func (q *Queries) GetDroplets(ctx context.Context) ([]Droplet, error) {
	rows, err := q.db.Query(ctx, getDroplets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Droplet
	for rows.Next() {
		var i Droplet
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Increases,
			&i.AmountCents,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDropletsByBucket = `-- name: GetDropletsByBucket :many
SELECT id, bucket_id, increases, amount_cents, created_at, metadata FROM droplets WHERE bucket_id = $1
`

func (q *Queries) GetDropletsByBucket(ctx context.Context, bucketID uuid.UUID) ([]Droplet, error) {
	rows, err := q.db.Query(ctx, getDropletsByBucket, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Droplet
	for rows.Next() {
		var i Droplet
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Increases,
			&i.AmountCents,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
