// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bucket struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Metadata  json.RawMessage
}

type Drip struct {
	ID          uuid.UUID
	DropletID   uuid.UUID
	Increases   bool
	AmountCents int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Metadata    json.RawMessage
}

type Droplet struct {
	ID                  uuid.UUID
	BucketID            uuid.UUID
	Name                string
	InitialBalanceCents int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Metadata            json.RawMessage
}
